# Generated by Django 6.1 on 2026-09-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_department_category_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
