# Generated by Django 6.1 on 2026-09-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
    ]
