# Generated by Django 6.1 on 2026-09-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_remove_department_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
